touch/urls.py
from django.contrib import admin
from django.urls import include, path
from django.contrib.auth import views as auth_views
from praise.api import PraiseResource
from people.api import UserResource

user_resource = UserResource()
praise_resource = PraiseResource()

urlpatterns = [
    path('people/', include('people.urls')),
    path('feedback/', include('feedback.urls')),
    path('praise/', include('praise.urls')),
    path('upvote/', include('upvote.urls')),
    path('oauth2', include('social_django.urls', namespace='social')),
    path('api/v1/', include(user_resource.urls)),
    path('api/v1/', include(praise_resource.urls)),
    path('admin/', admin.site.urls),
    path('', include('people.urls')),
]

upvote/urls.py
from django.urls import path

from . import views

app_name = 'upvote'
urlpatterns = [
	path('', views.index, name='index'),
]

upvote/models.py
from django.db import models
from people.models import User
from datetime import datetime

class Vote(models.Model):
    creator = models.ForeignKey(User, on_delete=models.DO_NOTHING, related_name="vote_creator")
    description = models.CharField(max_length=1000)
    taskid = models.CharField(max_length=10)
    timestamp = models.DateTimeField('timestamp', default=datetime.now)
    voters = models.ManyToManyField(User, related_name="vote_voters")
    def __str__(self):
        return self.taskid + "-" + self.creator.username

upvote/forms.py
from django import forms

class VoteForm(forms.Form):
    description = forms.CharField(widget=forms.Textarea(), max_length=250, label="Suggestion")
    taskid = forms.CharField(max_length=10, label="Phabricator Task ID:")
    

upvote/views.py
from django.shortcuts import render
from django.utils import timezone
from django.contrib.auth.decorators import login_required
from django.db.models import Count

from people.models import User
from .forms import VoteForm
from .models import Vote

@login_required
def index(request):

    if request.method=='POST':
        creator = request.user
        form = VoteForm(request.POST)
        if form.is_valid():
            vote = Vote(creator = creator, description=form.cleaned_data["description"], taskid=form.cleaned_data["taskid"], timestamp=timezone.now())
            vote.save()
            vote.voters.add(creator)
            vote.save()

            form = VoteForm()
    else:
        form = VoteForm()


    # approve response #XXX this could be done better - in REST?
    if request.GET and 'id' in request.GET.keys():
        vote = Vote.objects.filter(pk=request.GET['id'])[0]
        vote.voters.add(request.user)
        vote.save()
    
    votes = Vote.objects.annotate(num_votes=Count('voters')).order_by('-num_votes')

    context = { 'form' : form, 'votes' : votes } 
    return render(request, 'upvote/index.html', context)

upvote/templates/upvote/index.html
{% extends "base.html" %}
<title>touch:upvote</title>

{% block content %}
<section class="content">
        <form id="form-upvote" action="{% url 'upvote:index' %}" method="post">
            {% csrf_token %}
            {{ form }}
            <input class="btn-submit" type="submit" value="Submit">
        </form>

        <footer>
        </footer>

        {% for v in votes %}
				<p>  <span class="upvote"> {{ v.voters.count }}
                    {% if user not in v.voters.all %}
                    <a href="/upvote/?id={{ v.id }}" class="upvote">&#x21E7;</a>
                    {% else %}
                        <span style="color: #8c7c8e">&#x21E7; </span>
                    {% endif %}
                    </span> <strong> <a href="https://phabricator.collabora.com/{{ v.taskid }}">{{ v.description }}</a></strong>.
				<span style="color: #8c7c8e"> By {{ v.creator.name }} ({{v.timestamp}})</span></p>
					<br />
					
			{% empty %}
				<p>No suggestions yet.</p>
			{% endfor %}

</section>
{% endblock %}