people/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from . import views

app_name = 'people'
urlpatterns = [
	path('', views.index, name='people'),
	path('login/', auth_views.LoginView.as_view(template_name='people/login.html')),
	path('logout/', auth_views.LogoutView.as_view(template_name='people/login.html')),
	path('apikey/', views.apikey, name='apikey'),
	path('mentees/', views.MenteesView.as_view(template_name='people/mentees_list.html'), name='mentees'),
	path('<str:username>/', views.profile, name='profile'),

]

praise/urls.py
from django.urls import path

from . import views

app_name = 'praise'
urlpatterns = [
	path('', views.index, name='index'),
]

touch/urls.py
from django.contrib import admin
from django.urls import include, path
from django.contrib.auth import views as auth_views
from praise.api import PraiseResource
from people.api import UserResource

user_resource = UserResource()
praise_resource = PraiseResource()

urlpatterns = [
    path('people/', include('people.urls')),
    path('feedback/', include('feedback.urls')),
    path('praise/', include('praise.urls')),
    path('upvote/', include('upvote.urls')),
    path('oauth2', include('social_django.urls', namespace='social')),
    path('api/v1/', include(user_resource.urls)),
    path('api/v1/', include(praise_resource.urls)),
    path('admin/', admin.site.urls),
    path('', include('people.urls')),
]

praise/models.py
from django.db import models
from people.models import User
from datetime import datetime

# Create your models here.
class Praise(models.Model):
    giver = models.ForeignKey(User, on_delete=models.DO_NOTHING, related_name="praise_giver")
    receiver = models.ForeignKey(User, on_delete=models.DO_NOTHING, related_name="praise_receiver")
    text = models.CharField(max_length=1000)
    timestamp = models.DateTimeField('timestamp', default=datetime.now)
    client = models.CharField(max_length=100, default='')
    def __str__(self):
        return self.giver.username + "-" + self.receiver.username

praise/forms.py
from django import forms
from people.models import User

class PraiseForm(forms.Form):
    receiver = forms.ChoiceField(required=False)
    text = forms.CharField(widget=forms.Textarea(attrs={'placeholder': 'Write kudos they deserve here...'}), max_length=1000, label="Praise")

praise/views.py
from django.shortcuts import render
from django.http import StreamingHttpResponse
from django.utils import timezone
from django.views.decorators.csrf import csrf_exempt
from django.contrib.auth.decorators import login_required
from django.conf import settings
from django.core.mail import send_mail
from django.db.models import Count

import requests
import json
from datetime import datetime, timedelta

from .models import Praise
from people.models import User
from .forms import PraiseForm

def post_kudos_url(giver, receiver, text):
    headers = {'Content-type': 'application/json'}
    post_data = {}
    post_data['icon_url'] = "https://touch.collabora.com/static/img/favicon.ico"
    post_data['text'] = ":tada: :tada: :tada: [**kudos!**](https://touch.collabora.com/praise/) - from @" + giver.username + " to :medal_sports: **@" + receiver.username + "** \n>" + text
    r = requests.post(settings.KUDOS_WEBHOOK, json.dumps(post_data), headers=headers)

def send_kudos_email(praise):
    message = '''
    Hello, {0}

    You have received a new kudos from {1}:

    "{2}"

    Go to https://touch.collabora.com/praise/ to see all kudos.

    Thank you for being part of our Feedback Culture! Give feedback to someone at https://touch.collabora.com/feedback.
    '''
    send_mail(
        'You received a new kudos!',
         message.format(praise.receiver.first_name, praise.giver.name(), praise.text),
        'noreply@touch.collabora.com',
        [praise.receiver.username + '@collabora.com'],
        fail_silently=False,
    )

def choices_list(giver):
    l = []
    for u in User.objects.exclude(username=giver.username).filter(is_active=True).order_by('first_name'):
        l.append(tuple((u.id, u.name)))
    return l

@login_required
def index(request):
    giver = request.user

    if request.method=='POST':
        form = PraiseForm(request.POST)
        form.fields['receiver'].choices = choices_list(giver)
        if form.is_valid():
             receiver = User.objects.filter(id=form.cleaned_data['receiver'])[0]
             praise = Praise(giver=giver, receiver=receiver, text=form.cleaned_data["text"], timestamp=timezone.now(), client="web")
             praise.save()

             post_kudos_url(giver, receiver, form.cleaned_data["text"])
             form = PraiseForm()
             send_kudos_email(praise)
    else:
        form = PraiseForm()

    kudos = Praise.objects.order_by('timestamp').reverse()

    form.fields['receiver'].choices = choices_list(giver)
    context =  {'kudos': kudos, 'form': form }

    all_top_receivers = User.objects.annotate(num_kudos=Count('praise_receiver')).order_by('-num_kudos')[:10]
    all_top_givers = User.objects.annotate(num_kudos=Count('praise_giver')).order_by('-num_kudos')[:10]

    period = datetime.today() - timedelta(days=90)
    last3_top_receivers = User.objects.filter(praise_receiver__timestamp__gte=period).annotate(num_kudos=Count('praise_receiver')).order_by('-num_kudos')[:10]
    last3_top_givers = User.objects.filter(praise_giver__timestamp__gte=period).annotate(num_kudos=Count('praise_giver')).order_by('-num_kudos')[:10]

    context['all_top_receivers'] = all_top_receivers
    context['all_top_givers'] = all_top_givers
    context['last3_top_receivers'] = last3_top_receivers
    context['last3_top_givers'] = last3_top_givers

    return render(request, 'praise/index.html', context)

praise/templates/praise/index.html
{% extends "base.html" %}
<title>touch:praise</title>

<script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
<!-- Select2 component -->
<link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.6-rc.0/css/select2.min.css" rel="stylesheet" />
<script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.6-rc.0/js/select2.min.js"></script>

{% block content %}
<section class="content">
    <form id="form-praise" action="{% url 'praise:index' %}" method="post">
        {% csrf_token %}
	{{ form }}
	<input class="btn-submit" type="submit" value="Submit">
      </form>
        <footer>
        </footer>

		<div class="container_grid">
		<div class="col1">

			{% for k in kudos %}
				<p><strong>&#x2B50;<a href="{% url 'people:profile' k.giver.username %}">{{ k.giver.name }}</a></strong> to 
					<strong><a href="{% url 'people:profile' k.receiver.username %}">{{ k.receiver.name }}</a></strong>: {{k.text}}
				<span style="color: #8c7c8e"> ({{k.timestamp}})</span></p>
					<br />
					
			{% empty %}
				<p>No responses yet.</p>
			{% endfor %}

		</div>
		<div class="col2">
			<h2>top 10 givers last 3 months</h2>
			{% for k in last3_top_givers %}
				{{k.num_kudos}} {{k.name}} <br />
			{% endfor %}

			<h2>top 10 receivers last 3 months</h2>
			{% for k in last3_top_receivers %}
				{{k.num_kudos}} {{k.name}} <br />
			{% endfor %}
			<h2>top 10 givers all-time</h2>
			{% for k in all_top_givers %}
				{{k.num_kudos}} {{k.name}} <br />
			{% endfor %}

			<h2>top 10 receivers all-time</h2>
			{% for k in all_top_receivers %}
				{{k.num_kudos}} {{k.name}} <br />
			{% endfor %}
		</div>
		</div>

</section>
{% endblock %}